import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>nv just testing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            lyo lyo lyo lyo,&nbsp;
            <code className={styles.code}>ye bhi meri galti hai</code>
          </p>
          <div>
            <Link
              href="#"
              rel="noopener noreferrer"
              onClick={() => alert("Hey!")}
            >
              By <h2>NV</h2>
            </Link>
          </div>
        </div>

        <div className={styles.center}>
          <h1>NV JUST TESTING</h1>
        </div>

        <div className={styles.grid}>
          <div className={styles.card} rel="noopener noreferrer">
            <h2 className={inter.className}>
              One <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </div>

          <div className={styles.card} rel="noopener noreferrer">
            <h2 className={inter.className}>
              Two <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </div>

          <div className={styles.card} rel="noopener noreferrer">
            <h2 className={inter.className}>
              Ka <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </div>

          <div className={styles.card} rel="noopener noreferrer">
            <h2 className={inter.className}>
              Four <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
